### ISSUE TITLE
latest gem is slow

### ISSUE THREAD

**Issue by ahoward** [thibaudgg/rb-fsevent#43]
i use rb-fsevent for rego

  https://github.com/ahoward/rego

after upgrading i was seeing extremely sluggish responses

i'm playing locally with the following config in an attempt to make the lib more reactive

``` ruby

   trap('SIGINT'){ exit!(42) }

    fsevent.watch(
      directories,
        :latency => 0.00042,
        :no_defer => true,
        :file_events => true,
        :watch_root => true,
        :since_when => 0
    ) do |*args|

      p :args => args

   end

```

but there seems to be some baked in max of about a second: i can't seem to process events faster than that....

i scanned the code and did not see anything obvious, so i thought i'd drop this in a ticket and ask for help

**Comment by ttilley** [comment]
I think that this is beyond my ability to do anything about. if you're already using "no defer" then there's not much else you can do.

however... file level events, which you look to have enabled, are so incredibly rapid fire that you might simply be bogging down ruby itself processing them all one at a time. things make have improved since my first experiments, but a simple file rename would fire off like 10 events at once which is seriously painful to process when not coalesced. that may be more the source of your issue than anything else. in this case, i assure you, you want a much higher latency setting... and that it's a good thing.

please forgive me, but this library will be largely deprecated within a few months in favor of a version that's FFI based (which may or may not increase responsiveness for you but will absolutely resolve several unrelated issues). as such, i need to mark this as will-not-fix.
