### ISSUE TITLE
signal handling incorrectly eats ctrl-c

### ISSUE THREAD

**Issue by ahoward** [thibaudgg/rb-fsevent#44]
causing

https://github.com/guard/listen/issues/105

**Comment by ttilley** [comment]
signal handling has been completely rewritten since this issue was filed, and i sincerely apologize for not having responded to this.

the `rb-fsevent` library will be largely deprecated within a few months in favor of a version that makes use of FFI, where this bug wouldn't even be possible as there's no passing on of signals to subprocesses.
