### ISSUE TITLE
Deletes not triggering over AFP

### ISSUE THREAD

**Issue by ryanstout** [thibaudgg/rb-fsevent#51]
I've got a shared drive (AFP) that I'm tracking changes on.  Say I copy in a folder with images in it to the shared folder, when the folder is deleted from another computer via finder (on the shared drive over AFP), I get a deleted event for all files, but not for the folder that contained them (and was also deleted).  Any ideas why this might be?

Thanks

**Comment by ttilley** [comment]
i apologize for the long delay on this. i'm cleaning house on the issue tracker. 

`rb-fsevent` doesn't work even remotely consistently on remote filesystems. this is something i have no control over. you may need to force whatever higher level library or application you're using to use polling instead of the fsevents API.

again, I am sorry for not having responded to this earlier. I doubt this comes as much comfort 3 whole years later...
