### ISSUE TITLE
Receiving SIGQUIT crashes entire windowserver

### ISSUE THREAD

**Issue by CamJN** [thibaudgg/rb-fsevent#68]
There's a bug in macOS 10.12.4, that manifests like this: when fsevent_watch receives a SIGQUIT it (either directly or indirectly I'm not sure) crashes the WindowServer, which takes all gui applications down with it.

I'm going to write this up for Apple too, but since they are often slow to fix things and this will continue to affect anyone on 10.12.4 (possibly other versions, I'm not fond of triggering the bug to test it obviously).

Let me know if there's more info you'd like me to provide.

**Comment by ttilley** [comment]
*blank stare*

What the FUCK?!

With the recent changes in MacOS since 10.12, it is no longer possible for me to hotpatch low level functionality without it triggering a security fault. There is literally no path for me to fix this whatsoever, even if I were able to. (fsevent_watch already uses low level API patching to fix 10.7-10.11 regarding an issue with HFS+ caching breaking the case of some paths... and it took YEARS to get that problem properly diagnosed, fixed, and sent upstream for Apple to fix in 10.12...)

If this is true then it is, quite possibly, the most fucked up issue I've heard of in MacOS. It shouldn't be possible under any condition. An Apple support request is honestly your only option for getting this fixed. I'm sorry I can't help more. If you have a dev license then you have at least 2 direct support requests a year to get in touch with the developers themselves (this may have changed since I signed up).

**Comment by ttilley** [comment]
I'm also running 10.12.5 beta (16F71b) so I may not be able to reproduce.

**Comment by ttilley** [comment]
It may help if you inform them that ALL ruby applications that monitor the filesystem make use of fsevent_watch via rb-fsevent (whether they use FSSM or Guard/Listen). That should light a fire under them if nothing else does.

**Comment by CamJN** [comment]
Oh they're taking it seriously, but they need logs from the event and I've been too busy these last few days to have time to deliberately cause crashes like this.

**Comment by ttilley** [comment]
glad to hear that they're taking it seriously. please update this ticket with any useful information you can.

please bear in mind that if you're obligated not to release specific information due to your contract with Apple, that mentioning anything here can negatively impact your standing with Apple. Make sure you can actually share the information you post here.

**Comment by CamJN** [comment]
So it turns out that this was a misunderstanding, I thought the signal was going to the fsevent_watch pid but it was going to -1, which resulted in what looked like a WindowServer crash.
